-- migration: standardize table names, drop old profile and keep singular naming

/*
We previously ended up with two tables:
  - public.profile   (permission-related profile)
  - public.profiles  (user-profile generated by trigger)

This causes confusion.  The goal of this migration is to
standardize on conventional singular names and avoid the
collision:

  * remove the old `profile` table entirely
  * rename the new `profiles` table to `profile` (singular)

If you actually meant to keep the permission table instead,
adjust accordingly.

Note: any foreign keys or triggers referencing `profiles`
will need to be updated manually after renaming (not handled
here); in our current schema they only exist on the trigger
function created in a previous migration, so that function
should be re‑created separately if necessary.
*/

-- drop the legacy permission table
-- (if you still need it, you should create a new one with a
-- different name before running this migration)
drop table if exists public.profile cascade;

-- rename the actual user profile table to singular
-- and adjust its primary key constraint name if necessary
alter table if exists public.profiles
  rename to profile;

-- optionally, rename the primary key constraint (Postgres
-- will auto‑generate a name like profiles_pkey, so we fix it)
alter table if exists public.profile
  rename constraint profiles_pkey to profile_pkey;

-- NOTE: triggers/functions that inserted into public.profiles
-- must be updated separately.  If you have a trigger such as
-- on_auth_user_created, drop & recreate it in a later migration
-- using the new table name (this file intentionally doesn't
-- touch them to avoid ordering issues).
